###########################################################
#
# Automations - automations.yaml
#
###########################################################


- alias: 'Daylights'
  trigger:
    platform: sun
    event: sunset
    offset: "-01:30:00"
  condition: 
    condition: state
    entity_id: group.all_devices
    state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.daytime
    
- alias: 'Nightlights'
  trigger:
    platform: sun
    event: sunset
    offset: "+00:00:00"
  condition: 
    condition: state
    entity_id: group.all_devices
    state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.evenings
    
- alias: 'Movie Time on'
  trigger:
    platform: state
    entity_id: media_player.roku_5s56ae167930
    to: playing
    for:
      seconds: "3"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: time
        after: "20:00:00"
      - condition: state
        entity_id: light.bubble_lamp
        state: "on"
  action:
    service: scene.turn_on
    entity_id: scene.movie_time
    
- alias: 'Movie Time off'
  trigger:
    platform: state
    entity_id: media_player.roku_5s56ae167930
    from: playing
    to: home
    for:
      seconds: "20"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: light.bubble_lamp
        state: "on"
  action:
    service: scene.turn_on
    entity_id: scene.evenings_quick
    

###########################################################
#
# Presence based automations
#
###########################################################


- alias: 'Welcome Home evenings'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
    for:
      minutes: 1
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:45:00"
  action:
    service: scene.turn_on
    entity_id: scene.evenings_quick
    

###########################################################
#
#  Presence based notifications
#
###########################################################

    
- alias: 'Motoz home zone leave test'
  trigger:
    platform: state
    entity_id: device_tracker.motoz
    from: 'home'
    to: 'not_home'
    for:
      minutes: 1
  action:
    service: script.zanzito_send_notification
    data:
      dest_id: '6272b1f8e7150a5'
      message: 'See you later'

- alias: 'Motoz home zone arrive test'
  trigger:
    platform: state
    entity_id: device_tracker.motoz
    from: 'not_home'
    to: 'home'
    for:
      minutes: 1
  action:
    service: script.zanzito_send_notification
    data:
      dest_id: '6272b1f8e7150a5'
      message: 'Welcome home'
      
- alias: 'Motog home zone leave test'
  trigger:
    platform: state
    entity_id: device_tracker.motog
    from: 'home'
    to: 'not_home'
    for:
      minutes: 1
  action:
    service: script.zanzito_send_notification
    data:
      dest_id: '976607fbc133630'
      message: 'See you later, have a nice day'

- alias: 'Motog home zone arrive test'
  trigger:
    platform: state
    entity_id: device_tracker.motog
    from: 'not_home'
    to: 'home'
    for:
      minutes: 1
  action:
    service: script.zanzito_send_notification
    data:
      dest_id: '976607fbc133630'
      message: 'Welcome home'

- alias: 'Motog left work'
  trigger:
    platform: zone
    entity_id: device_tracker.motog
    zone: zone.jewels
    event: leave
  condition:
    condition: time
    after: '17:30:00'
    weekday:
      - wed
      - fri
      - sat
      - sun
  action:
    service: script.zanzito_send_notification
    data:
      dest_id: '6272b1f8e7150a5'
      message: 'Cutie is leaving work'

- alias: 'Motoz left work'
  trigger:
    platform: zone
    entity_id: device_tracker.motoz
    zone: zone.work
    event: leave
  action:
    service: script.zanzito_send_notification
    data:
      dest_id: '976607fbc133630'
      message: 'Mr is leaving work'