###########################################################
#
# Automations - automations.yaml
#
###########################################################


- alias: 'Turn on the lights when the sun sets'
  trigger:
    platform: sun
    event: sunset
    offset: "-01:30:00"
  condition: 
    condition: state
    entity_id: group.all_devices
    state: 'home'
  action:
    - service: light.turn_on
      data:
        entity_id: 'light.bubble_lamp'
        brightness_pct: "80"
        transition: "300"
    - service: light.turn_on
      data:
        entity_id: 'light.grey_ikea_lamp'
        transition: "120"
        brightness_pct: "80"
        color_temp: "390"
    - service: light.turn_on
      data:
        entity_id: 'light.leaf_lamp'
        transition: "120"
        brightness_pct: "90"
        color_temp: "390"
    - service: light.turn_on
      data:
        entity_id: 'light.bubble_lamp'
        transition: "120"
        brightness_pct: "50"
        color_temp: "390"
      
      
###########################################################
#
# Presence based automations
#
###########################################################


- alias: 'Welcome Home evenings'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
    for:
      minutes: 1
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:45:00"
  action:
    - service: light.turn_on
      entity_id: light.bubble_lamp
      data:
        brightness_pct: "40"
        transition: "5"
    - service: light.turn_on
      entity_id: 
        - light.leaf_lamp
        - light.grey_ikea_lamp
      data:
        brightness_pct: "70"
        transition: "5"
    - service: switch.turn_on
      entity_id: switch.christmas_lights


###########################################################
#
#  Presence based notifications
#
###########################################################

    
- alias: 'Motoz home zone leave test'
  trigger:
    platform: state
    entity_id: device_tracker.motoz
    from: 'home'
    to: 'not_home'
    for:
      minutes: 1
  action:
    service: script.zanzito_send_notification
    data:
      dest_id: '6272b1f8e7150a5'
      message: 'See you later'

- alias: 'Motoz home zone arrive test'
  trigger:
    platform: state
    entity_id: device_tracker.motoz
    from: 'not_home'
    to: 'home'
    for:
      minutes: 1
  action:
    service: script.zanzito_send_notification
    data:
      dest_id: '6272b1f8e7150a5'
      message: 'Welcome home'
      
- alias: 'Motog home zone leave test'
  trigger:
    platform: state
    entity_id: device_tracker.motog
    from: 'home'
    to: 'not_home'
    for:
      minutes: 1
  action:
    service: script.zanzito_send_notification
    data:
      dest_id: '976607fbc133630'
      message: 'See you later, have a nice day'

- alias: 'Motog home zone arrive test'
  trigger:
    platform: state
    entity_id: device_tracker.motog
    from: 'not_home'
    to: 'home'
    for:
      minutes: 1
  action:
    service: script.zanzito_send_notification
    data:
      dest_id: '976607fbc133630'
      message: 'Welcome home'

- alias: 'Motog left work'
  trigger:
    platform: zone
    entity_id: device_tracker.motog
    zone: zone.jewels
    event: leave
  condition:
    condition: time
    after: '17:30:00'
    weekday:
      - wed
      - fri
      - sat
      - sun
  action:
    service: script.zanzito_send_notification
    data:
      dest_id: '6272b1f8e7150a5'
      message: 'Cutie is leaving work'

- alias: 'Motoz left work'
  trigger:
    platform: zone
    entity_id: device_tracker.motoz
    zone: zone.work
    event: leave
  action:
    service: script.zanzito_send_notification
    data:
      dest_id: '976607fbc133630'
      message: 'Mr is leaving work'