###########################################################
# 
# Binary Sensors binary_sensors.yaml
#
###########################################################


- platform: mqtt
  name: "Motoz orientation"
  state_topic: "zanzito/6272b1f8e7150a5/flat_down"
  payload_on: "1"
  payload_off: "0"
  value_template: '{{ value_json.value0 }}'