###########################################################
#
# Home Assistant Main Configuration file
#
###########################################################


homeassistant:
  name: Citadel
  latitude: !secret secret_latitude
  longitude: !secret secret_longitude
  elevation: 10
  unit_system: imperial
  time_zone: !secret secret_timezone
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

http:
  api_password: !secret secret_api_password
  ssl_certificate: !secret secret_ssl_certificate
  ssl_key: !secret secret_ssl_key
  base_url: !secret secret_base_url
  trusted_networks: !secret secret_trusted_networks
  ip_ban_enabled: True
  login_attempts_threshold: 5

frontend:

config:

updater:

conversation:

recorder:

history:

logbook:

sun:


###########################################################
#
# Components
#
###########################################################


tts:
  platform: google

mqtt:
  broker: !secret secret_mqtt_broker
  port: !secret secret_mqtt_port
  client_id: !secret secret_mqtt_client_id
  username: !secret secret_mqtt_username
  password: !secret secret_mqtt_password

tradfri:
  host: !secret tradfri_ip_address
  allow_tradfri_groups: false
  
google_assistant:
  project_id: !secret ga_project_id
  client_id: !secret ga_client_id
  access_token: !secret ga_access_token
  exposed_domains:
    - switch
    - light
    - scene
  

###########################################################
#
# Includes
#
###########################################################


zone: !include zones.yaml

binary_sensor: !include binary_sensor.yaml

sensor: !include sensors.yaml
  
device_tracker: !include device_trackers.yaml

media_player: !include media_players.yaml

switch: !include switches.yaml

script: !include scripts.yaml

group: !include groups.yaml

automation: !include automation.yaml