### device_trackers.yaml

# - platform: snmp
  # host: !secret secret_snmp_host
  # community: !secret secret_community
  # baseoid: 1.3.6.1.2.1.4.22.1.2
  # track_new_devices: false
#  consider_home: 60
  
- platform: mqtt_json
  devices:
    motoz: zanzito/6272b1f8e7150a5/location
    motog: zanzito/976607fbc133630/location